### ISSUE TITLE
need to merge terms- amelia cleft lip palate hydrocephalus iris coloboma and ACLH

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo-build#104]
MONDO_0022434 amelia cleft lip palate hydrocephalus iris coloboma was brought in from gard, but also exists in OMIM (OMIM 601357) - it is MONDO_0011052 ACLH.

These two records should be merged.

**Comment by cmungall** [comment]
@GARDInfoCenter - it's this one:
https://rarediseases.info.nih.gov/diseases/641/amelia-cleft-lip-palate-hydrocephalus-iris-coloboma
