### ISSUE TITLE
"Parkinson disease, late-onset"  and "late onset Parkinson disease"

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/mondo-build#113]
When debugging https://github.com/monarch-initiative/monarch-app/issues/1561, I noticed there are two terms:
MONDO:0008199 ! Parkinson disease, late-onset 
MONDO:0018466 ! late onset Parkinson disease

MONDO:0018466 is a direct subclass of rare parkinsonian syndrome due to neurodegenerative disease, where as MONDO:0008199 is a direct subclass of rare genetic parkinsonian disorder.

MONDO:0008199 has the eqs:
OMIM:168600
UMLS:C3160718

MONDO:0018466 has the eqs:
Orphanet:411602
SCTID:716662004
DOID:0060892

#### MONDO:0008199
![mondo 0008199](https://user-images.githubusercontent.com/1467299/37857681-70bc290e-2eba-11e8-8202-656f1c12068f.png)

#### MONDO:0018466
![mondo 0018466](https://user-images.githubusercontent.com/1467299/37857684-7258fe22-2eba-11e8-8393-e078747108cd.png)

**Comment by cmungall** [comment]
Current approach is to make MONDO:0018466 explicitly inherited late-onset, but there is still a case for merging
