### ISSUE TITLE
X-linked ID, Cabezas type

### ISSUE THREAD

**Issue by ErinRiggs** [monarch-initiative/mondo-build#30]
Hello.  I am looking through some genes on the ClinGen ID/Autism gene curation group's list for curation, and came across CUL4B.  I notice that there are two MONDO terms that look very similar - is there a difference between the two?  If not, can they be merged into a single entity?  At a quick glance, it looks as though there is one MONDO entry directly corresponding to the OMIM term, and another directly corresponding to the ORPHA term.

Here they are in MONDO:
![image](https://user-images.githubusercontent.com/30054804/33098434-0c5b8168-ced3-11e7-9d65-cb125e937763.png)
Here is what it looks like in OMIM:
![image](https://user-images.githubusercontent.com/30054804/33098454-21823bcc-ced3-11e7-8626-b620b3594063.png)
And ORPHANET (note that ORPHANET cross-references the same OMIM term above, but OMIM does not appear to cross-reference ORPHA):
![image](https://user-images.githubusercontent.com/30054804/33098501-3a45581a-ced3-11e7-86e7-4efedcbe82cc.png)

Thanks,
Erin

**Comment by cmungall** [comment]
good catch, thank you. fix is in source and will be in next release. Use MONDO:0010306 (the one with orphanet definition)
