### ISSUE TITLE
X-linked syndromic intellectual disability

### ISSUE THREAD

**Issue by ErinRiggs** [monarch-initiative/mondo-build#31]
Hello.  Similar to my previous ticket, I am reviewing potential disease terms for the ClinGen ID/Autism group to use when entering into our Gene Curation Interface.  One term that we plan to use is "X-linked syndromic intellectual disability."  I notice that there are two similar-sounding terms with different MONDO IDs - what is the difference between the two?  If there is no difference, can they by merged?

![image](https://user-images.githubusercontent.com/30054804/33098749-1ace93b0-ced4-11e7-8589-fd829b533de3.png)

Thanks,
Erin

**Comment by cmungall** [comment]
Thanks! go ahead and use MONDO:0020119. MONDO:0000738 will be obsolete in the next release
