### ISSUE TITLE
test new version in OLS

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo-build#4]
Everything should work fine in OLS but should check.

Note: the obo file has annotated xrefs, for tracked sources (OMIM,DOID,EFO,Orphanet,soon NCIT) there should be an annotation stating equiv/sub/super. These correspond precisely to the logical axioms. @simonjupp would you prefer non-equivs filtered out? Assume you will continue to consume the .obo for now.

It would be good to test pre/mondo.obo too
http://obofoundry.org/ontology/mondo.html

**Comment by simonjupp** [comment]
It got loaded ok last night.

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_5044

It seems odd that DOID_5044 has an xref to itself. The other xrefs have a source, are these all assumed to be equivalent?

OLS actually managed to pick the source up by accident. It has an assumption that the value of any axiom annotation found on a OBO dbxref APs is the OBO dbxref "description". It also only expects there to be one, so it doesn't show them when there are multiple sources. I'll create a ticket for OLS to handle this a bit better as we'll want to mine these for when we suck them into OxO.

**Comment by cmungall** [comment]
> It seems odd that DOID_5044 has an xref to itself

in the source, this is a mondo class with a DOID xref. For the release we merge things back to a clique leader which is doid here (note we aim to tackle NCIT properly later). So expected but nonetheless weird. Can fix but this is a temp issue as we'll eventually switch IDs
