### ISSUE TITLE
Question about MONDO_0008840 ataxia telangiectasia

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo-build#42]
the subclass assertion below seems wrong, but I can't determine what the underlying cause is.

![image](https://user-images.githubusercontent.com/6722114/33639572-cf75c04c-d9e0-11e7-8752-ae6bf964130e.png)

**Comment by cmungall** [comment]
Good catch, you can see that this has a low prob associated with it, so this is ranked high in the list of things to investigate

>  I can't determine what the underlying cause is.

See the editors manual. You can see the provenance of the xrefs that were used as seed interpretation as axioms. You will see that Orphanet called Orphanet:100 - OMIM:208900 as 'e'. But I think this is a common problem to interpret the OMIM as more generic than it is based on name.

**Comment by cmungall** [comment]
actually in this case we agree with the 'e'. we should treat the variant using the variant pattern

**Comment by cmungall** [comment]
note also, Orphanet includes http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=251347 "ataxia-telangiectasia-like disorder". It would seem from the name this would be a good grouping for the variant term. However, Orphanet has no children here. It also says it is neonatal which conflicts with typical onset for variant.

this orphanet xrefs https://omim.org/entry/604391 ATAXIA-TELANGIECTASIA-LIKE DISORDER 1; ATLD1

we also have https://omim.org/entry/208910 "ATAXIA-TELANGIECTASIA WITH GENERALIZED SKIN PIGMENTATION AND EARLY DEATH"

is this at AT-like disorder? or an AT-variant? Or is it a subtype of AT?
