### ISSUE TITLE
Create disjoint siblings for testing purposes

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo-build#52]
Currently robot and owltools have a facility to test if two named classes are inferred equivalent. E.g. if we have

this is still a valid OWL ontology:

```
Ont1:Cat SubClassOf Ont1:Mammal
Ont2:Cat SubClassOf Ont2:Mammal
Ont1:Cat EquivalentTo Ont2:Mammal
Ont1:Mammal EquivalentTo Ont2:Cat
```

 It is formally coherent (since SubClassOf is reflexive). Even though it is not intentional (everything ends up in a big equivalence clique)

robot reason will flag this. However, it would be better if we could formally treat ontologies like this as formally incoherent. It's easier to debug in Protege for example (they appear under Nothing in inferred view).

The way to do this is to treat every SubClassOf in an ontology as meaning ProperSubClassOf (i.e `<` not `<=`).

This can be done by giving every class a disjoint sibling for every parent they have

e.g.

```
Ont1:Cat-Sibling SubClassOf Ont1:Mammal
Ont1:Cat-Sibling DisjointWith Ont1:Cat
```

this is sufficient to render the combined ontology as formally incoherent as intended.

**Comment by cmungall** [comment]
This is the query

```
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
  ?sibClass a owl:Class ;
            owl:disjointWith ?c ;
            rdfs:subClassOf ?p ;
            rdfs:label ?sibLabel
}
WHERE {
 ?c rdfs:subClassOf ?p
 NOT EXISTS { ?c owl:deprecated "true"^^xsd:boolean }
 OPTIONAL {
   ?c rdfs:label ?clabel
   BIND(concat("DISJOINT-SIB-OF ", ?clabel) AS ?sibLabel)
 }
 BIND (UUID() as ?sibClass)
}
```

**Comment by balhoff** [comment]
Do you want to add:

```sparql
FILTER(isIRI(?c))
FILTER(isIRI(?p))
```

?

**Comment by cmungall** [comment]
quite right.

Initially thought that making all asserted SubClassOf assertions non-reflexive was desirable. But that actually messes with ontologies that have a `X-part EquivalentTo part-of some X` pattern. It probably wouldn't affect GO since we have a genus in the definition (the disjoint sibling of X-part would include things like atoms that are part of X). But still it's overreach.
