### ISSUE TITLE
Review class EHLERS-DANLOS SYNDROME, BEASLEY-COHEN TYPE

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo-build#91]
(From @pnrobinson:) EHLERS-DANLOS SYNDROME, BEASLEY-COHEN TYPE is n=1 disease

...we have not found an n=2 since the original publication in 1979, means probably that this OMIM entry needs to be retired, but I think for MONDO we

need to deal with n=1 cases, and we should figure out a way of labelling this.

_This can be addressed by adding an n=1 subset tag, yes?_

**Comment by cmungall** [comment]
Yes, add to the subset. Also consider annotation the axiom with evidence (e.g. paper in the OMIM record, or a TAS from Peter)

**Comment by nicolevasilevsky** [comment]
Hi @cmungall I am still getting a weird diff when I try to edit MONDO on a branch. Would you mind taking a look?

BICB119:ontology vasilevs$ git diff
diff --git a/src/ontology/mondo-edit.obo b/src/ontology/mondo-edit.obo
index d8fb95f..09e41e9 100644
--- a/src/ontology/mondo-edit.obo
+++ b/src/ontology/mondo-edit.obo
@@ -136687,7 +136687,6 @@ subset: gard_rare {source="GARD:0006975"}
 subset: ordo_clinical_subtype {source="Orphanet:284963"}
 subset: ordo_disease {source="Orphanet:558"}
 subset: prototype_pattern {source="https://github.com/monarch-initiative/monarch-disease-ontology/issues/101"}
-property_value: excluded_synonym "Contractural arachnodactyly" xsd:string {source="GARD:0006975"}
 synonym: "MARFAN SYNDROME" RELATED [MONDO:Lexical, OMIM:154700]
 synonym: "Marfan syndrome type 1" RELATED [Orphanet:284963]
 synonym: "Marfan Syndrome, Type 1" RELATED [OMIM:154700]
@@ -136724,6 +136723,7 @@ is_a: MONDO:0020236 {source="Orphanet:558"} ! lens position anomaly
 is_a: MONDO:0020272 {source="Orphanet:558"} ! connective tissue disease with eye involvement
 relationship: disease_has_basis_in_dysfunction_of NCBIGene:2200 {source="mim2gene_medgen"}
 property_value: confidence "0.014130103558823048" xsd:double
+property_value: excluded_synonym "Contractural arachnodactyly" xsd:string {source="GARD:0006975"}
 property_value: seeAlso https://rarediseases.info.nih.gov/diseases/6975/marfan-syndrome xsd:anyURI {source="GARD:0006975"}
 
 [Term]
@@ -225215,6 +225215,7 @@ is_a: MONDO:0005579 {source="DC-OMIM:608762"} ! generalised epilepsy
 [Term]
 id: MONDO:0012114
 name: Ehlers-Danlos syndrome, Beasley-Cohen type
+subset: n_of_one
 synonym: "Ehlers-Danlos Syndrome With Mental Retardation, Deafness, and Cataract" RELATED [OMIM:608763]
 synonym: "EHLERS-DANLOS SYNDROME, BEASLEY-COHEN TYPE" RELATED [OMIM:608763]
 xref: MESH:C536199 {source="MONDO:ontobio", source="MONDO:equivalentTo"}

**Comment by cmungall** [comment]
try it now

**Comment by nicolevasilevsky** [comment]
working now, thank you!
